language: android
sudo: false
android:
  components:
    - platform-tools
    - build-tools-23.0.0
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
before_script:
  - android list targets
