CREATE TABLE IF NOT EXISTS FavoriteStops (Id INTEGER PRIMARY KEY AUTOINCREMENT, code VARCHAR NOT NULL ON CONFLICT FAIL UNIQUE ON CONFLICT FAIL, isFavorited INTEGER NOT NULL ON CONFLICT FAIL);

INSERT INTO FavoriteStops (id, code, isFavorited) SELECT Id as id, code, isFavorited FROM StopFavorites;

DROP TABLE StopFavorites;